<?php

return [
    "vin"                    => "VIN",
    "make"                   => "Make",
    "manufacturer"           => "Manufacturer",
    "country"                => "Plant Country",
    "manufacturer_address"   => "Manufacturer Address",
    "model"                  => "Model",
    "series"                 => "Series",
    "check_digit"            => "Check Digit",
    "sequential_number"      => "Sequential Number",
    "body"                   => "Body",
    "length"                 => "Length (mm)",
    "width"                  => "Width (mm)",
    "height"                 => "Height (mm)",
    "max_speed"              => "Max Speed (km/h)",
    "type"                   => "Product Type",
    "model_year"             => "Model Year",
    "number_of_seats"        => "Number of Seats",
    "number_of_doors"        => "Number of Doors",
    "number_of_axles"        => "Number of Axles",
    "wheelbase"              => "Wheelbase (mm)",
    "wheel_size"             => "Wheel Size",
    "transmission"           => "Transmission",
    "abs"                    => "ABS",
    "max_roof_load"          => "Max roof load (kg)",
    "permitted_trailer_load" => "Permitted trailer load without brakes (kg)",
    "drive"                  => "Drive",
    "steering_type"          => "Steering Type",
];
